services:
  db:
    image: postgres:17.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=localpassword
      - POSTGRES_USER=localuser
      - POSTGRES_DB=localdb
    restart: unless-stopped
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    env_file:
      - .env.local
    environment:
      - DB_HOST=db
      - DB_NAME=localdb
      - DB_USER=localuser
      - DB_PASSWORD=localpassword
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:

# docker compose -f docker-compose.local.yml run --rm web python manage.py setupdata